export default {

  PROFILES_RECEIVED:'PROFILES_RECEIVED',
  PROFILE_SELECTED:'PROFILE_SELECTED',
  PROFILE_CREATED:'PROFILE_CREATED',
  CURRENT_USER_RECEIVED:'CURRENT_USER_RECEIVED',
  BOOKMARKS_RECEIVED:'BOOKMARK_RECEIVED',
  BOOKMARK_CREATED:'BOOKMARK_CREATED'

}
